### ISSUE TITLE
running long query and short query concurrently fails when both are shuffle-heavy

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria#583]
Q1: the oceanography example on https://demo.myria.cs.washington.edu/editor, `MyriaL` language.

Q2: `Triangles(x,y,z) :- twitter_1m(x,y), twitter_1m(y,z), twitter_1m(z,x).` in `Datalog`.

When I run Q1 normally, it takes about 2.5 minutes and then finishes.
When I run Q2 normally, it takes about 10-20 seconds and then finishes.

When I start Q1, then start Q2, Q2 shows up as `RUNNING` for a very long time -- until Q1 finishes -- and then it fails immediately. Q1 usually succeeds.

The reason for the failure of Q2 varies, but usually looks like a networking issue. For instance:

``` java
edu.washington.escience.myria.DbException: Query #21138.0 failed
    at edu.washington.escience.myria.parallel.MasterSubQuery$WorkerExecutionInfo$2.operationComplete(MasterSubQuery.java:105)
    at edu.washington.escience.myria.parallel.LocalSubQueryFutureListener.operationComplete(LocalSubQueryFutureListener.java:45)
    at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListener(OperationFutureBase.java:583)
    at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListeners(OperationFutureBase.java:542)
    at edu.washington.escience.myria.util.concurrent.OperationFutureBase.wakeupWaitersAndNotifyListeners(OperationFutureBase.java:151)
    at edu.washington.escience.myria.util.concurrent.OperationFutureBase.setFailure0(OperationFutureBase.java:506)
    at edu.washington.escience.myria.parallel.LocalSubQueryFuture.setFailure(LocalSubQueryFuture.java:69)
    at edu.washington.escience.myria.parallel.MasterSubQuery.workerFail(MasterSubQuery.java:322)
    at edu.washington.escience.myria.parallel.Server$MessageProcessor.run(Server.java:185)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at edu.washington.escience.myria.util.concurrent.RenamingThreadFactory$1.run(RenamingThreadFactory.java:33)
    Suppressed: edu.washington.escience.myria.DbException: Worker #6 failed: null
        at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1125)
        at java.util.Collections$SetFromMap.add(Collections.java:3903)
        at edu.washington.escience.myria.parallel.LocalFragmentResourceManager.startAStream(LocalFragmentResourceManager.java:63)
        at edu.washington.escience.myria.operator.network.Producer.createANewChannel(Producer.java:227)
        at edu.washington.escience.myria.operator.network.Producer.init(Producer.java:213)
        at edu.washington.escience.myria.operator.Operator.open(Operator.java:395)
        at edu.washington.escience.myria.parallel.LocalFragment.init(LocalFragment.java:637)
        at edu.washington.escience.myria.parallel.WorkerSubQuery.init(WorkerSubQuery.java:211)
        at edu.washington.escience.myria.parallel.WorkerSubQuery.init(WorkerSubQuery.java:198)
        at edu.washington.escience.myria.parallel.WorkerShortMessageProcessor.processQueryMessage(WorkerShortMessageProcessor.java:81)
        at edu.washington.escience.myria.parallel.WorkerShortMessageProcessor.processMessage(WorkerShortMessageProcessor.java:48)
        at edu.washington.escience.myria.parallel.ipc.IPCMessageHandler.receiveRegisteredData(IPCMessageHandler.java:180)
        at edu.washington.escience.myria.parallel.ipc.IPCMessageHandler.messageReceived(IPCMessageHandler.java:246)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
        ... 3 more
    Caused by: java.lang.NullPointerException
        ... 23 more
```

I believe I have also seen errors related to `no physical IO channel`, but I am not certain.

**Comment by vitorglemos** [comment]
I am facing an error similar to this. The error occurs when I run Triangle query (Q2) and TPC-DS queries (even after handling the null fields). I have also seen errors related to `no physical IO channel`. Is there any solution for this? I realize that when running these queries, some worker nodes fail for some reason.
