### ISSUE TITLE
profiling multiple resources leads to weird bugs

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria#687]
@stechu @jingjingwang I feel like one of you was onto this issue at one point.

There seems to be some race condition whereby the profiler will cancel its own insertion statements leading to errors like this:

```
edu.washington.escience.myria.DbException: Query #61928.26 failed
	at edu.washington.escience.myria.parallel.MasterSubQuery$WorkerExecutionInfo$2.operationComplete(MasterSubQuery.java:100)
	at edu.washington.escience.myria.parallel.LocalSubQueryFutureListener.operationComplete(LocalSubQueryFutureListener.java:45)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListener(OperationFutureBase.java:583)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListeners(OperationFutureBase.java:542)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.wakeupWaitersAndNotifyListeners(OperationFutureBase.java:151)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.setFailure0(OperationFutureBase.java:506)
	at edu.washington.escience.myria.parallel.LocalSubQueryFuture.setFailure(LocalSubQueryFuture.java:69)
	at edu.washington.escience.myria.parallel.MasterSubQuery.workerFail(MasterSubQuery.java:317)
	at edu.washington.escience.myria.parallel.QueryManager.workerFailed(QueryManager.java:308)
	at edu.washington.escience.myria.parallel.Server$MessageProcessor.run(Server.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at edu.washington.escience.myria.util.concurrent.RenamingThreadFactory$1.run(RenamingThreadFactory.java:33)
	Suppressed: edu.washington.escience.myria.DbException: Worker #40 failed: ErrorCode: 0, SQLState: 57014, Msg: Batch entry 9,073 INSERT INTO "public:logs:Sending" ("queryId","subQueryId","fragmentId","nanoTime","numTuples","destWorkerId") VALUES (61928,26,2,3053488126,172,49) was aborted.  Call getNextException to see the cause.
  ErrorCode: 0, SQLState: 57014, Msg:   ERROR: canceling statement due to user request
		at edu.washington.escience.myria.util.ErrorUtils.mergeSQLException(ErrorUtils.java:60)
		at edu.washington.escience.myria.accessmethod.JdbcAccessMethod.tupleBatchInsert(JdbcAccessMethod.java:201)
		at edu.washington.escience.myria.profiling.ProfilingLogger.flush(ProfilingLogger.java:249)
		at edu.washington.escience.myria.profiling.ProfilingLogger.recordSent(ProfilingLogger.java:197)
		at edu.washington.escience.myria.operator.network.GenericShuffleProducer.consumeTuples(GenericShuffleProducer.java:102)
		at edu.washington.escience.myria.operator.RootOperator.fetchNextReady(RootOperator.java:123)
		at edu.washington.escience.myria.operator.Operator.nextReady(Operator.java:335)
		at edu.washington.escience.myria.parallel.LocalFragment.executeActually(LocalFragment.java:458)
		at edu.washington.escience.myria.parallel.LocalFragment.access$400(LocalFragment.java:43)
		at edu.washington.escience.myria.parallel.LocalFragment$1.call(LocalFragment.java:195)
		at edu.washington.escience.myria.parallel.LocalFragment$1.call(LocalFragment.java:175)
		at edu.washington.escience.myria.util.concurrent.ExecutableExecutionFuture.call(ExecutableExecutionFuture.java:193)
		... 4 more
	Caused by: edu.washington.escience.myria.DbException: ErrorCode: 0, SQLState: 57014, Msg: Batch entry 9,073 INSERT INTO "public:logs:Sending" ("queryId","subQueryId","fragmentId","nanoTime","numTuples","destWorkerId") VALUES (61928,26,2,3053488126,172,49) was aborted.  Call getNextException to see the cause.
  ErrorCode: 0, SQLState: 57014, Msg:   ERROR: canceling statement due to user request
```

IIRC it had something to do with verifying that the profiler's JDBC connection was still live. Do you remember what the issue was and whether it has been solved?

**Comment by domoritz** [comment]
Don't we use normal batch insert? I don't remember anything about this issue.
