### ISSUE TITLE
Worker mismatch / single plan fragment when combining Singleton & UnionAll operators

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria#704]
The following query fails when attempting to union a single tuple with a relation that is distributed across multiple workers:

```
relation = scan(dwtsample);
extended = unionall([0.0, 0.0], relation);
store(extended, result);
```

The singleton appears to assert when running on multiple workers, but the unionall requires all workers on which the larger relation is defined.  I assume a multi-fragment plan is required here?

Full exception below:

```
java.lang.IllegalArgumentException: Fragment 0 has a singleton operator 1, but workers [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 16, 19, 18, 21, 20, 23, 22, 25, 24, 27, 26, 29, 28, 31, 30, 34, 35, 32, 33, 38, 39, 36, 37, 42, 43, 40, 41, 46, 47, 44, 45, 51, 50, 49, 48, 55, 54, 53, 52, 59, 58, 57, 56, 63, 62, 61, 60, 68, 69, 70, 71, 64, 65, 66, 67, 72]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at edu.washington.escience.myria.api.encoding.QueryConstruct.setAndVerifySingletonConstraints(QueryConstruct.java:326)
	at edu.washington.escience.myria.api.encoding.QueryConstruct.assignWorkersToFragments(QueryConstruct.java:428)
	at edu.washington.escience.myria.api.encoding.QueryConstruct.instantiate(QueryConstruct.java:73)
	at edu.washington.escience.myria.parallel.JsonSubQuery.instantiate(JsonSubQuery.java:63)
	at edu.washington.escience.myria.parallel.Query.nextSubQuery(Query.java:202)
	at edu.washington.escience.myria.parallel.QueryManager.advanceQuery(QueryManager.java:322)
	at edu.washington.escience.myria.parallel.QueryManager.finishQuery(QueryManager.java:140)
	at edu.washington.escience.myria.parallel.QueryManager.access$300(QueryManager.java:40)
	at edu.washington.escience.myria.parallel.QueryManager$1.operationComplete(QueryManager.java:381)
	at edu.washington.escience.myria.parallel.LocalSubQueryFutureListener.operationComplete(LocalSubQueryFutureListener.java:45)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListener(OperationFutureBase.java:583)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListeners(OperationFutureBase.java:542)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.wakeupWaitersAndNotifyListeners(OperationFutureBase.java:151)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.setFailure0(OperationFutureBase.java:506)
	at edu.washington.escience.myria.parallel.LocalSubQueryFuture.setFailure(LocalSubQueryFuture.java:69)
	at edu.washington.escience.myria.parallel.MasterSubQuery$WorkerExecutionInfo$2.operationComplete(MasterSubQuery.java:98)
	at edu.washington.escience.myria.parallel.LocalSubQueryFutureListener.operationComplete(LocalSubQueryFutureListener.java:45)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListener(OperationFutureBase.java:583)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListeners(OperationFutureBase.java:542)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.wakeupWaitersAndNotifyListeners(OperationFutureBase.java:151)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.setFailure0(OperationFutureBase.java:506)
	at edu.washington.escience.myria.parallel.LocalSubQueryFuture.setFailure(LocalSubQueryFuture.java:69)
	at edu.washington.escience.myria.parallel.MasterSubQuery.workerFail(MasterSubQuery.java:317)
	at edu.washington.escience.myria.parallel.QueryManager.workerFailed(QueryManager.java:306)
	at edu.washington.escience.myria.parallel.Server$MessageProcessor.run(Server.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at edu.washington.escience.myria.util.concurrent.RenamingThreadFactory$1.run(RenamingThreadFactory.java:33)
```

(Originally observed by @jesscs)

**Comment by stechu** [comment]
Looks like a raco bug.

**Comment by dhalperi** [comment]
This is a pretty thorny issue that we'll need to work out some day (I'll embellish it in an issue on the raco repo)... there are related bugs that are currently __un-detectable__ in raco. But, I fixed it with a workaround in production now.

**Comment by dhalperi** [comment]
Thanks @jesscs and @BrandonHaynes
