### ISSUE TITLE
travis fails on jsonQuerySubmitTest sometimes

### ISSUE THREAD

**Issue by jingjingwang** [uwescience/myria#708]
I got this sometimes from travis, but not always:

edu.washington.escience.myria.systemtest.JsonQuerySubmitTest > jsonQuerySubmitTest FAILED
java.lang.AssertionError: expected:<SUCCESS> but was:<ACCEPTED>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at edu.washington.escience.myria.systemtest.JsonQuerySubmitTest.jsonQuerySubmitTest(JsonQuerySubmitTest.java:197)

**Comment by jingjingwang** [comment]
E.g. https://travis-ci.org/uwescience/myria/jobs/53118968
