### ISSUE TITLE
Query explosion with Boolean comparison in predicate

### ISSUE THREAD

**Issue by BrandonHaynes** [uwescience/myria#738]
Consider the following query:

```Python
T1 = [True as x];
T2 = [from T1 where x emit *];
store(T2, T2);
```

This fails during execution with the following error:

```
edu.washington.escience.myria.DbException: Query #181.0 failed: Call compile first or copy the data if it is the same in the input.
	at edu.washington.escience.myria.parallel.MasterSubQuery$WorkerExecutionInfo$2.operationComplete(MasterSubQuery.java:105)
	at edu.washington.escience.myria.parallel.LocalSubQueryFutureListener.operationComplete(LocalSubQueryFutureListener.java:45)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListener(OperationFutureBase.java:583)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListeners(OperationFutureBase.java:542)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.wakeupWaitersAndNotifyListeners(OperationFutureBase.java:151)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.setFailure0(OperationFutureBase.java:506)
	at edu.washington.escience.myria.parallel.LocalSubQueryFuture.setFailure(LocalSubQueryFuture.java:69)
	at edu.washington.escience.myria.parallel.MasterSubQuery.workerFail(MasterSubQuery.java:320)
	at edu.washington.escience.myria.parallel.QueryManager.workerFailed(QueryManager.java:308)
	at edu.washington.escience.myria.parallel.Server$MessageProcessor.run(Server.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at edu.washington.escience.myria.util.concurrent.RenamingThreadFactory$1.run(RenamingThreadFactory.java:33)
	Suppressed: edu.washington.escience.myria.DbException: Worker #2 failed: Call compile first or copy the data if it is the same in the input.
		at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
		at edu.washington.escience.myria.expression.evaluate.BooleanEvaluator.eval(BooleanEvaluator.java:65)
		at edu.washington.escience.myria.operator.Filter.fetchNextReady(Filter.java:52)
		at edu.washington.escience.myria.operator.Operator.nextReady(Operator.java:336)
		at edu.washington.escience.myria.operator.RootOperator.fetchNextReady(RootOperator.java:120)
		at edu.washington.escience.myria.operator.Operator.nextReady(Operator.java:336)
		at edu.washington.escience.myria.parallel.LocalFragment.executeActually(LocalFragment.java:459)
		at edu.washington.escience.myria.parallel.LocalFragment.access$400(LocalFragment.java:44)
		at edu.washington.escience.myria.parallel.LocalFragment$1.call(LocalFragment.java:196)
		at edu.washington.escience.myria.parallel.LocalFragment$1.call(LocalFragment.java:176)
		at edu.washington.escience.myria.util.concurrent.ExecutableExecutionFuture.call(ExecutableExecutionFuture.java:193)
		... 4 more
	Caused by: java.lang.IllegalArgumentException: Call compile first or copy the data if it is the same in the input.
		... 15 more
```

Note that an explicit comparison fails with a different exception:

```Python
T1 = [True as x];
T2 = [from T1 where x == True emit *];
store(T2, JustX);
```

Exception:

```
edu.washington.escience.myria.DbException: Query #183.0 failed: EqualsExpression cannot handle left child [edu.washington.escience.myria.expression.VariableExpression@774ff130] of Type BOOLEAN_TYPE
	at edu.washington.escience.myria.parallel.MasterSubQuery$WorkerExecutionInfo$2.operationComplete(MasterSubQuery.java:105)
	at edu.washington.escience.myria.parallel.LocalSubQueryFutureListener.operationComplete(LocalSubQueryFutureListener.java:45)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListener(OperationFutureBase.java:583)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.notifyListeners(OperationFutureBase.java:542)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.wakeupWaitersAndNotifyListeners(OperationFutureBase.java:151)
	at edu.washington.escience.myria.util.concurrent.OperationFutureBase.setFailure0(OperationFutureBase.java:506)
	at edu.washington.escience.myria.parallel.LocalSubQueryFuture.setFailure(LocalSubQueryFuture.java:69)
	at edu.washington.escience.myria.parallel.MasterSubQuery.workerFail(MasterSubQuery.java:320)
	at edu.washington.escience.myria.parallel.QueryManager.workerFailed(QueryManager.java:308)
	at edu.washington.escience.myria.parallel.Server$MessageProcessor.run(Server.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at edu.washington.escience.myria.util.concurrent.RenamingThreadFactory$1.run(RenamingThreadFactory.java:33)
	Suppressed: edu.washington.escience.myria.DbException: Worker #2 failed: EqualsExpression cannot handle left child [edu.washington.escience.myria.expression.VariableExpression@774ff130] of Type BOOLEAN_TYPE
		at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
		at edu.washington.escience.myria.expression.BinaryExpression.checkAndReturnDefaultNumericType(BinaryExpression.java:183)
		at edu.washington.escience.myria.expression.BinaryExpression.checkAndReturnDefaultNumericType(BinaryExpression.java:165)
		at edu.washington.escience.myria.expression.ComparisonExpression.getOutputType(ComparisonExpression.java:62)
		at edu.washington.escience.myria.expression.Expression.getOutputType(Expression.java:124)
		at edu.washington.escience.myria.expression.evaluate.Evaluator.getOutputType(Evaluator.java:73)
		at edu.washington.escience.myria.expression.evaluate.BooleanEvaluator.<init>(BooleanEvaluator.java:33)
		at edu.washington.escience.myria.operator.Filter.init(Filter.java:78)
		at edu.washington.escience.myria.operator.Operator.open(Operator.java:403)
		at edu.washington.escience.myria.operator.Operator.open(Operator.java:393)
		at edu.washington.escience.myria.parallel.LocalFragment.initActually(LocalFragment.java:708)
		at edu.washington.escience.myria.parallel.LocalFragment.access$700(LocalFragment.java:44)
		at edu.washington.escience.myria.parallel.LocalFragment$2.call(LocalFragment.java:225)
		at edu.washington.escience.myria.parallel.LocalFragment$2.call(LocalFragment.java:218)
		at edu.washington.escience.myria.util.concurrent.ExecutableExecutionFuture.call(ExecutableExecutionFuture.java:193)
		... 4 more
	Caused by: java.lang.IllegalArgumentException: EqualsExpression cannot handle left child [edu.washington.escience.myria.expression.VariableExpression@774ff130] of Type BOOLEAN_TYPE
		... 19 more
```

**Comment by domoritz** [comment]
The second error makes sense. You shouldn't do comparison with booleans (at least not send that expression). See code in https://github.com/uwescience/myria/blob/master/src/edu/washington/escience/myria/expression/ComparisonExpression.java#L57.

**Comment by domoritz** [comment]
I'm out for the summer and won't work on this. Sorry.

**Comment by jingjingwang** [comment]
@domoritz Sure, it's not urgent. We were discussing who should be the best person for it and we agreed to be you :) If you find some time and don't mind to take a look, that would be great. (After this summer, of course)
