### ISSUE TITLE
Semantic errors in UDA/UDFs should fail query

### ISSUE THREAD

**Issue by senderista** [uwescience/myria#793]
A recent query (https://rest.myria.cs.washington.edu:1776/query/query-89177), containing a UDA with schema-incompatible return type, hung forever, throwing an exception on every tuple, rather than being terminated and reporting the error:
```
ERROR 2016-01-19 00:13:00,693 [Master message processor#0] Server$MessageProcessor - Worker #63 failed in executing query #89176.8.
edu.washington.escience.myria.DbException: Error updating UDA state
        at edu.washington.escience.myria.operator.agg.UserDefinedAggregator.addRow(UserDefinedAggregator.java:68)
        at edu.washington.escience.myria.operator.agg.MultiGroupByAggregate.updateGroup(MultiGroupByAggregate.java:191)
        at edu.washington.escience.myria.operator.agg.MultiGroupByAggregate.fetchNextReady(MultiGroupByAggregate.java:121)
        at edu.washington.escience.myria.operator.Operator.nextReady(Operator.java:336)
        at edu.washington.escience.myria.operator.RootOperator.fetchNextReady(RootOperator.java:120)
        at edu.washington.escience.myria.operator.Operator.nextReady(Operator.java:336)
        at edu.washington.escience.myria.parallel.LocalFragment.executeActually(LocalFragment.java:462)
        at edu.washington.escience.myria.parallel.LocalFragment.access$400(LocalFragment.java:47)
        at edu.washington.escience.myria.parallel.LocalFragment$1.call(LocalFragment.java:199)
        at edu.washington.escience.myria.parallel.LocalFragment$1.call(LocalFragment.java:179)
        at edu.washington.escience.myria.util.concurrent.ExecutableExecutionFuture.call(ExecutableExecutionFuture.java:193)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at edu.washington.escience.myria.util.concurrent.RenamingThreadFactory$1.run(RenamingThreadFactory.java:33)
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
        at edu.washington.escience.myria.storage.Tuple.getLong(Tuple.java:94)
        at SC.evaluate(Unknown Source)
        at edu.washington.escience.myria.operator.agg.UserDefinedAggregator.addRow(UserDefinedAggregator.java:65)
        ... 14 more
```
For reference, here is the query:
```
ranges = scan(armbrustlab:seaflow:adjusted_range_minmax_extent_v5);

max_ranges = select fsc_max + abs(fsc_min) as max_fsc, 
            cl_max + abs(chl_min) as max_chl,
            pe_max + abs(pe_min) as max_pe 
            from ranges;

-- Load the existing dataset
AllData = scan(armbrustlab:seaflow:adjusted_particles_byfile_untrans_v5);

total_particles = select count(*) as total, cruise, file_time
                    from AllData;

-- Assign a linear value into one of 16 bins 0..15
-- N.B.: // is integer division
def makebins(x,y): x//(y/16);
-- for defined width bins, replace (y/16) with the bin width

-- For each cruise & sample (day + file _id)
-- break the 3-D cytogram given by forward scatter,
-- chlorophyll, and phycoerythrin into a 16x16x16
-- bin space and count the number of cells in each bin.
AllDataBinned = select d.cruise, d.file_time,
                       makebins(d.fsc_adj,r.max_fsc) as fsc_bin,
                       makebins(d.chl_adj,r.max_chl) as chl_bin,
                       makebins(d.pe_adj,r.max_pe) as pe_bin,
                       count(*) as num_p
                       from AllData as d, max_ranges as r;

def pi(x,y): (x/y)*(log(x/y));

-- Compute the Richness N0 as the number of full bins
diversity = select cruise, file_time,
                  count(*) as N0,
                  -sum(pi(a.num_p,t.total)) as H,
                  -sum(pi(a.num_p,t.total))/log(count(*)) as J
                  from AllDataBinned as a, total_particles as t
                  where a.cruise = t.cruise 
                  and a.file_time = t.file_time;

store(diversity, diversity_untrans_max_scaled_16bins_v5);
```

**Comment by bmyerz** [comment]
@senderista Can you point me to the wrong return type in the above example? And in your opinion, should Raco catch this early?

**Comment by senderista** [comment]
This was a total brain fart on my part. I was looking at the wrong query in the logs. The exception trace above refers to https://rest.myria.cs.washington.edu:1776/query/query-89176, which indeed had a bad UDA and failed immediately as expected.
